/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FixedRouteImport } from './routes/fixed'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as DataManagementRouteImport } from './routes/data-management'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMoveGoalFundsRouteImport } from './routes/api/public/move-goal-funds'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedRoute = FixedRouteImport.update({
  id: '/fixed',
  path: '/fixed',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const DataManagementRoute = DataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMoveGoalFundsRoute = ApiPublicMoveGoalFundsRouteImport.update({
  id: '/api/public/move-goal-funds',
  path: '/api/public/move-goal-funds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/data-management': typeof DataManagementRoute
  '/debts': typeof DebtsRoute
  '/fixed': typeof FixedRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/paths': typeof PathsRoute
  '/review': typeof ReviewRoute
  '/transactions': typeof TransactionsRoute
  '/api/public/move-goal-funds': typeof ApiPublicMoveGoalFundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/data-management': typeof DataManagementRoute
  '/debts': typeof DebtsRoute
  '/fixed': typeof FixedRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/paths': typeof PathsRoute
  '/review': typeof ReviewRoute
  '/transactions': typeof TransactionsRoute
  '/api/public/move-goal-funds': typeof ApiPublicMoveGoalFundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/data-management': typeof DataManagementRoute
  '/debts': typeof DebtsRoute
  '/fixed': typeof FixedRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/paths': typeof PathsRoute
  '/review': typeof ReviewRoute
  '/transactions': typeof TransactionsRoute
  '/api/public/move-goal-funds': typeof ApiPublicMoveGoalFundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/data-management'
    | '/debts'
    | '/fixed'
    | '/goals'
    | '/import'
    | '/paths'
    | '/review'
    | '/transactions'
    | '/api/public/move-goal-funds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/data-management'
    | '/debts'
    | '/fixed'
    | '/goals'
    | '/import'
    | '/paths'
    | '/review'
    | '/transactions'
    | '/api/public/move-goal-funds'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/data-management'
    | '/debts'
    | '/fixed'
    | '/goals'
    | '/import'
    | '/paths'
    | '/review'
    | '/transactions'
    | '/api/public/move-goal-funds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DataManagementRoute: typeof DataManagementRoute
  DebtsRoute: typeof DebtsRoute
  FixedRoute: typeof FixedRoute
  GoalsRoute: typeof GoalsRoute
  ImportRoute: typeof ImportRoute
  PathsRoute: typeof PathsRoute
  ReviewRoute: typeof ReviewRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiPublicMoveGoalFundsRoute: typeof ApiPublicMoveGoalFundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed': {
      id: '/fixed'
      path: '/fixed'
      fullPath: '/fixed'
      preLoaderRoute: typeof FixedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-management': {
      id: '/data-management'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof DataManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/move-goal-funds': {
      id: '/api/public/move-goal-funds'
      path: '/api/public/move-goal-funds'
      fullPath: '/api/public/move-goal-funds'
      preLoaderRoute: typeof ApiPublicMoveGoalFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DataManagementRoute: DataManagementRoute,
  DebtsRoute: DebtsRoute,
  FixedRoute: FixedRoute,
  GoalsRoute: GoalsRoute,
  ImportRoute: ImportRoute,
  PathsRoute: PathsRoute,
  ReviewRoute: ReviewRoute,
  TransactionsRoute: TransactionsRoute,
  ApiPublicMoveGoalFundsRoute: ApiPublicMoveGoalFundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
